let productData = [
  {
    productName: "Zhiyun-Tech Gimbal",
    productImg: "https://via.placeholder.com/250x180",
    productPrice: 200,
    category: "gimbal",
    quantity: 2,
    id: "1",
  },
  {
    productName: "Canon EOS 1500D",
    productImg: "https://via.placeholder.com/250x180",
    productPrice: 100,
    category: "camera",
    quantity: 3,
    id: "2",
  },
  {
    productName: "Canon EOS 700D",
    productImg: "https://via.placeholder.com/250x180",
    productPrice: 200,
    category: "camera",
    quantity: 4,
    id: "3",
  },
  {
    productName: "Nikon D3400",
    productImg: "https://via.placeholder.com/250x180",
    productPrice: 100,
    category: "camera",
    quantity: 2,
    id: "4",
  },
  {
    productName: "Zhiyun Crane 3 Gimbal",
    productImg: "https://via.placeholder.com/250x180",
    productPrice: 400,
    category: "gimbal",
    quantity: 2,
    id: "5",
  },
  {
    productName: "Godox 60W Flash Lite",
    productImg: "https://via.placeholder.com/250x180",
    productPrice: 50,
    category: "flash",
    quantity: 2,
    id: "6",
  },
  {
    productName: "Canon 60W Speed Lite",
    productImg: "https://via.placeholder.com/250x180",
    productPrice: 50,
    category: "flash",
    quantity: 4,
    id: "7",
  },
  {
    productName: "Canon 60W Speed Lite",
    productImg: "https://via.placeholder.com/250x180",
    productPrice: 50,
    category: "flash",
    id: "8",
  },
  {
    productName: "Canon 60W Speed Lite",
    productImg: "https://via.placeholder.com/250x180",
    productPrice: 60,
    category: "flash",
    id: "9",
  },
  {
    productName: "Canon 60W Speed Lite",
    productImg: "https://via.placeholder.com/250x180",
    productPrice: 80,
    category: "flash",
    id: "10",
  },
];

export default productData;
